import os
import threading
from datetime import datetime

try:
    from .models import db as db
except Exception:  # pragma: no cover
    db = None


_schema_initialized = False
_schema_init_lock = threading.Lock()


def _db_backend():
    database_url = (os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL") or "").strip().lower()
    if database_url.startswith(("postgresql://", "postgres://", "postgresql+psycopg://")):
        return "postgres"
    raise RuntimeError("DATABASE_URL (or POSTGRES_URL) must point to PostgreSQL.")


def _use_mysql():
    return True


def _is_mysql_backend():
    return False


def _is_postgres_backend():
    return _db_backend() == "postgres"


def _placeholder():
    return "%s" if _use_mysql() else "?"


def list_all_customers():
    conn = get_db()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM customers ORDER BY created_at DESC")
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def get_db():
    if _is_postgres_backend():
        import psycopg
        from psycopg.rows import dict_row

        raw_url = (os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL") or "").strip()
        if not raw_url:
            raise RuntimeError("DATABASE_URL or POSTGRES_URL is required for PostgreSQL connections.")

        conninfo = raw_url.replace("postgresql+psycopg://", "postgresql://", 1)
        if conninfo.startswith("postgres://"):
            conninfo = conninfo.replace("postgres://", "postgresql://", 1)

        conn = psycopg.connect(conninfo, row_factory=dict_row)
        conn.autocommit = False
        return conn
    raise RuntimeError("DATABASE_URL (or POSTGRES_URL) must point to PostgreSQL.")


def init_db(force=False):
    global _schema_initialized
    if _schema_initialized and not force:
        return

    with _schema_init_lock:
        if _schema_initialized and not force:
            return

    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _is_mysql_backend()
    is_postgres = _is_postgres_backend()
    id_column = (
        "INTEGER PRIMARY KEY AUTO_INCREMENT"
        if is_mysql
        else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if is_postgres
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    text_type = "LONGTEXT" if is_mysql else "TEXT"
    
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS items (
            id {id_column},
            etsy_listing_id VARCHAR(255) NOT NULL UNIQUE,
            title TEXT,
            description TEXT,
            price_amount VARCHAR(50),
            price_currency VARCHAR(10),
            image_url {text_type},
            etsy_url TEXT,
            updated_at VARCHAR(50)
        )
        """
    )
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS manual_products (
            id {id_column},
            name VARCHAR(500) NOT NULL,
            description TEXT NOT NULL,
            category TEXT,
            materials TEXT,
            width REAL,
            height REAL,
            depth REAL,
            price REAL NOT NULL,
            quantity INTEGER NOT NULL,
            is_featured INTEGER DEFAULT 0,
            created_at VARCHAR(50),
            updated_at VARCHAR(50)
        )
        """
    )
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS product_images (
            id {id_column},
            product_id INTEGER NOT NULL,
            image_url {text_type} NOT NULL,
            media_type VARCHAR(50) DEFAULT 'image',
            display_order INTEGER DEFAULT 0,
            FOREIGN KEY (product_id) REFERENCES manual_products(id) ON DELETE CASCADE
        )
        """
    )
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS customers (
            id {id_column},
            email VARCHAR(255) NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            first_name VARCHAR(120),
            last_name VARCHAR(120),
            phone VARCHAR(50),
            admin_notes TEXT,
            created_at VARCHAR(50),
            updated_at VARCHAR(50),
            last_login_at VARCHAR(50)
        )
        """
    )
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS customer_addresses (
            id {id_column},
            customer_id INTEGER NOT NULL,
            label VARCHAR(120),
            line1 VARCHAR(255) NOT NULL,
            line2 VARCHAR(255),
            city VARCHAR(120),
            state VARCHAR(120),
            postal_code VARCHAR(40),
            country VARCHAR(80),
            is_default INTEGER DEFAULT 0,
            created_at VARCHAR(50),
            updated_at VARCHAR(50),
            FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
        )
        """
    )
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS customer_password_resets (
            id {id_column},
            customer_id INTEGER NOT NULL,
            token_hash VARCHAR(128) NOT NULL UNIQUE,
            expires_at VARCHAR(50) NOT NULL,
            used_at VARCHAR(50),
            request_ip VARCHAR(100),
            user_agent VARCHAR(255),
            created_at VARCHAR(50) NOT NULL,
            FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
        )
        """
    )
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS customer_favorites (
            id {id_column},
            customer_id INTEGER NOT NULL,
            product_type VARCHAR(20) NOT NULL,
            product_id VARCHAR(64) NOT NULL,
            created_at VARCHAR(50),
            UNIQUE (customer_id, product_type, product_id),
            FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
        )
        """
    )

    if is_postgres:
        cursor.execute("ALTER TABLE customers ADD COLUMN IF NOT EXISTS admin_notes TEXT")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_password_resets_customer ON customer_password_resets(customer_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_password_resets_expires ON customer_password_resets(expires_at)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_password_resets_customer_created ON customer_password_resets(customer_id, created_at DESC)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customers_created_at ON customers(created_at DESC)")
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS customer_cart_items (
            id {id_column},
            customer_id INTEGER NOT NULL,
            product_type VARCHAR(20) NOT NULL,
            product_id VARCHAR(64) NOT NULL,
            quantity INTEGER DEFAULT 1,
            created_at VARCHAR(50),
            updated_at VARCHAR(50),
            UNIQUE (customer_id, product_type, product_id),
            FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
        )
        """
    )
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS customer_orders (
            id {id_column},
            customer_id INTEGER NOT NULL,
            order_number VARCHAR(50),
            status VARCHAR(30) DEFAULT 'pending',
            subtotal_amount REAL,
            shipping_amount REAL,
            tax_amount REAL,
            total_amount REAL,
            currency VARCHAR(10) DEFAULT 'USD',
            payment_status VARCHAR(30) DEFAULT 'pending',
            payment_provider VARCHAR(30),
            payment_reference VARCHAR(255),
            customer_name VARCHAR(160),
            customer_email VARCHAR(255),
            shipping_address TEXT,
            billing_address TEXT,
            notes TEXT,
            admin_seen INTEGER DEFAULT 0,
            admin_seen_at VARCHAR(50),
            created_at VARCHAR(50),
            updated_at VARCHAR(50),
            FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
        )
        """
    )
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS customer_order_items (
            id {id_column},
            order_id INTEGER NOT NULL,
            product_type VARCHAR(20) NOT NULL,
            product_id VARCHAR(64) NOT NULL,
            title TEXT,
            price REAL,
            quantity INTEGER DEFAULT 1,
            image_url TEXT,
            FOREIGN KEY (order_id) REFERENCES customer_orders(id) ON DELETE CASCADE
        )
        """
    )
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS customer_order_events (
            id {id_column},
            order_id INTEGER NOT NULL,
            event_type VARCHAR(80) NOT NULL,
            event_detail TEXT,
            payload TEXT,
            created_at VARCHAR(50),
            FOREIGN KEY (order_id) REFERENCES customer_orders(id) ON DELETE CASCADE
        )
        """
    )
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS customer_reviews (
            id {id_column},
            customer_id INTEGER NOT NULL,
            product_type VARCHAR(20) NOT NULL,
            product_id VARCHAR(64) NOT NULL,
            rating INTEGER NOT NULL,
            title VARCHAR(200),
            body TEXT,
            verified_purchase INTEGER DEFAULT 0,
            status VARCHAR(20) DEFAULT 'pending',
            created_at VARCHAR(50),
            updated_at VARCHAR(50),
            UNIQUE (customer_id, product_type, product_id),
            FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
        )
        """
    )
    conn.commit()

    if is_postgres:
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS subtotal_amount REAL")
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS shipping_amount REAL")
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS tax_amount REAL")
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS payment_status VARCHAR(30) DEFAULT 'pending'")
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS payment_provider VARCHAR(30)")
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(255)")
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS customer_name VARCHAR(160)")
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS customer_email VARCHAR(255)")
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS shipping_address TEXT")
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS billing_address TEXT")
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS notes TEXT")
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS admin_seen INTEGER DEFAULT 0")
        cursor.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS admin_seen_at VARCHAR(50)")
        cursor.execute("UPDATE customer_orders SET admin_seen = 0 WHERE admin_seen IS NULL")

        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_addresses_customer_default_created ON customer_addresses(customer_id, is_default DESC, created_at DESC)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_favorites_customer_created ON customer_favorites(customer_id, created_at DESC)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_cart_items_customer_updated ON customer_cart_items(customer_id, updated_at DESC)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_orders_customer_created ON customer_orders(customer_id, created_at DESC)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_orders_payment_reference ON customer_orders(payment_reference)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_orders_admin_seen_created ON customer_orders(admin_seen, created_at DESC)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_orders_unseen_created ON customer_orders(created_at DESC) WHERE admin_seen = 0")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_order_items_order ON customer_order_items(order_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_order_items_product_order ON customer_order_items(product_type, product_id, order_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_order_events_order ON customer_order_events(order_id)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_order_events_created ON customer_order_events(created_at)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_order_events_order_created ON customer_order_events(order_id, created_at DESC)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_reviews_product_status_created ON customer_reviews(product_type, product_id, status, created_at DESC)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_customer_reviews_customer_created ON customer_reviews(customer_id, created_at DESC)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_manual_products_created_at ON manual_products(created_at DESC)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_product_images_product_order ON product_images(product_id, display_order)")

    conn.commit()
    conn.close()
    _schema_initialized = True


def upsert_item(payload):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _is_mysql_backend()
    now = datetime.utcnow().isoformat()
    
    if is_mysql:
        # MySQL: use INSERT ... ON DUPLICATE KEY UPDATE
        cursor.execute(
            """
            INSERT INTO items (
                etsy_listing_id, title, description, price_amount,
                price_currency, image_url, etsy_url, updated_at
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            ON DUPLICATE KEY UPDATE
                title = VALUES(title),
                description = VALUES(description),
                price_amount = VALUES(price_amount),
                price_currency = VALUES(price_currency),
                image_url = VALUES(image_url),
                etsy_url = VALUES(etsy_url),
                updated_at = VALUES(updated_at)
            """,
            (
                payload["etsy_listing_id"],
                payload.get("title"),
                payload.get("description"),
                payload.get("price_amount"),
                payload.get("price_currency"),
                payload.get("image_url"),
                payload.get("etsy_url"),
                now,
            ),
        )
    else:
        # PostgreSQL/SQLite: use INSERT ... ON CONFLICT ... DO UPDATE
        placeholder = _placeholder()
        cursor.execute(
            f"""
            INSERT INTO items (
                etsy_listing_id,
                title,
                description,
                price_amount,
                price_currency,
                image_url,
                etsy_url,
                updated_at
            ) VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder})
            ON CONFLICT(etsy_listing_id) DO UPDATE SET
                title = excluded.title,
                description = excluded.description,
                price_amount = excluded.price_amount,
                price_currency = excluded.price_currency,
                image_url = excluded.image_url,
                etsy_url = excluded.etsy_url,
                updated_at = excluded.updated_at
            """,
            (
                payload["etsy_listing_id"],
                payload.get("title"),
                payload.get("description"),
                payload.get("price_amount"),
                payload.get("price_currency"),
                payload.get("image_url"),
                payload.get("etsy_url"),
                now,
            ),
        )
    
    conn.commit()
    placeholder = _placeholder()
    cursor.execute(
        f"SELECT id FROM items WHERE etsy_listing_id = {placeholder}",
        (payload["etsy_listing_id"],),
    )
    row = cursor.fetchone()
    item_id = row["id"] if row else getattr(cursor, "lastrowid", None)
    conn.close()
    return item_id


def fetch_items():
    conn = get_db()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM items ORDER BY updated_at DESC")
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def fetch_item(item_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(f"SELECT * FROM items WHERE id = {placeholder}", (item_id,))
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def create_manual_product(payload):
    import json
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_postgres = _is_postgres_backend()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    
    # Serialize category and materials if they are lists
    category = payload.get("category")
    if isinstance(category, list):
        category = json.dumps(category) if category else None
    
    materials = payload.get("materials")
    if isinstance(materials, list):
        materials = json.dumps(materials) if materials else None
    
    insert_values = (
        payload["name"],
        payload["description"],
        category,
        materials,
        payload.get("width"),
        payload.get("height"),
        payload.get("depth"),
        payload["price"],
        payload["quantity"],
        1 if payload.get("is_featured") else 0,
        now,
        now,
    )
    if is_postgres:
        cursor.execute(
            f"""
            INSERT INTO manual_products (
                name, description, category, materials,
                width, height, depth, price, quantity, is_featured,
                created_at, updated_at
            ) VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder},
                      {placeholder}, {placeholder}, {placeholder}, {placeholder},
                      {placeholder}, {placeholder}, {placeholder}, {placeholder})
            RETURNING id
            """,
            insert_values,
        )
        product_id = cursor.fetchone()["id"]
    else:
        cursor.execute(
            f"""
            INSERT INTO manual_products (
                name, description, category, materials,
                width, height, depth, price, quantity, is_featured,
                created_at, updated_at
            ) VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder},
                      {placeholder}, {placeholder}, {placeholder}, {placeholder},
                      {placeholder}, {placeholder}, {placeholder}, {placeholder})
            """,
            insert_values,
        )
        product_id = cursor.lastrowid
    
    # Insert images if provided
    images = payload.get("images", [])
    for idx, image in enumerate(images):
        cursor.execute(
            f"""
            INSERT INTO product_images (product_id, image_url, media_type, display_order)
            VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder})
            """,
            (product_id, image["url"], image.get("type", "image"), idx)
        )
    
    conn.commit()
    conn.close()
    return product_id


def fetch_manual_products():
    import json
    conn = get_db()
    cursor = conn.cursor()
    cursor.execute(
        """
        SELECT
            p.*,
            i.image_url AS product_image_url,
            i.media_type AS product_image_media_type
        FROM manual_products p
        LEFT JOIN product_images i ON i.product_id = p.id
        ORDER BY p.created_at DESC, i.display_order ASC
        """
    )
    rows = cursor.fetchall()

    products = []
    by_id = {}
    for row in rows:
        payload = dict(row)
        product_id = payload.get("id")

        product = by_id.get(product_id)
        if not product:
            payload.pop("product_image_url", None)
            payload.pop("product_image_media_type", None)
            product = payload

            if product.get("category"):
                try:
                    product["category"] = json.loads(product["category"])
                except (json.JSONDecodeError, TypeError):
                    pass

            if product.get("materials"):
                try:
                    product["materials"] = json.loads(product["materials"])
                except (json.JSONDecodeError, TypeError):
                    pass

            product["images"] = []
            by_id[product_id] = product
            products.append(product)

        image_url = payload.get("product_image_url")
        if image_url:
            product["images"].append(
                {
                    "image_url": image_url,
                    "media_type": payload.get("product_image_media_type") or "image",
                }
            )
    
    conn.close()
    return products


def fetch_manual_products_catalog():
    import json
    conn = get_db()
    cursor = conn.cursor()

    cursor.execute(
        """
        SELECT
            p.id,
            p.name,
            p.description,
            p.category,
            p.materials,
            p.width,
            p.height,
            p.depth,
            p.price,
            p.quantity,
            p.is_featured,
            p.created_at,
            p.updated_at,
            (
                SELECT pi.image_url
                FROM product_images pi
                WHERE pi.product_id = p.id
                ORDER BY pi.display_order
                LIMIT 1
            ) AS preview_image_url
        FROM manual_products p
        ORDER BY p.created_at DESC
        """
    )
    rows = cursor.fetchall()

    products = []
    for row in rows:
        product = dict(row)

        if product.get("category"):
            try:
                product["category"] = json.loads(product["category"])
            except (json.JSONDecodeError, TypeError):
                pass

        if product.get("materials"):
            try:
                product["materials"] = json.loads(product["materials"])
            except (json.JSONDecodeError, TypeError):
                pass

        preview_image_url = product.pop("preview_image_url", None)
        product["images"] = [{"image_url": preview_image_url, "media_type": "image"}] if preview_image_url else []
        products.append(product)

    conn.close()
    return products


def fetch_manual_product(product_id):
    import json
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    
    cursor.execute(
        f"SELECT * FROM manual_products WHERE id = {placeholder}", (product_id,)
    )
    row = cursor.fetchone()
    
    if not row:
        conn.close()
        return None
    
    product = dict(row)
    
    # Deserialize category and materials from JSON strings
    if product.get("category"):
        try:
            product["category"] = json.loads(product["category"])
        except (json.JSONDecodeError, TypeError):
            pass  # Keep as string if not valid JSON
    
    if product.get("materials"):
        try:
            product["materials"] = json.loads(product["materials"])
        except (json.JSONDecodeError, TypeError):
            pass  # Keep as string if not valid JSON
    
    # Fetch images for this product
    cursor.execute(
        f"SELECT image_url, media_type FROM product_images WHERE product_id = {placeholder} ORDER BY display_order",
        (product_id,)
    )
    images = cursor.fetchall()
    product["images"] = [dict(img) for img in images]
    
    conn.close()
    return product


def update_manual_product(product_id, payload):
    import json
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    
    # Serialize category and materials if they are lists
    category = payload.get("category")
    if isinstance(category, list):
        category = json.dumps(category) if category else None
    
    materials = payload.get("materials")
    if isinstance(materials, list):
        materials = json.dumps(materials) if materials else None
    
    cursor.execute(
        f"""
        UPDATE manual_products
        SET name = {placeholder}, description = {placeholder}, category = {placeholder}, materials = {placeholder},
            width = {placeholder}, height = {placeholder}, depth = {placeholder}, price = {placeholder}, quantity = {placeholder},
            is_featured = {placeholder}, updated_at = {placeholder}
        WHERE id = {placeholder}
        """,
        (
            payload["name"],
            payload["description"],
            category,
            materials,
            payload.get("width"),
            payload.get("height"),
            payload.get("depth"),
            payload["price"],
            payload["quantity"],
            1 if payload.get("is_featured") else 0,
            now,
            product_id,
        ),
    )
    
    # Update images if provided
    if "images" in payload:
        # Delete old images
        cursor.execute(f"DELETE FROM product_images WHERE product_id = {placeholder}", (product_id,))
        # Insert new images
        for idx, image in enumerate(payload["images"]):
            # Handle both new uploads (with "url" and "type") and existing images (with "image_url" and "media_type")
            image_url = image.get("url") or image.get("image_url")
            media_type = image.get("type") or image.get("media_type", "image")
            
            if image_url:  # Only insert if we have a valid image URL
                cursor.execute(
                    f"""
                    INSERT INTO product_images (product_id, image_url, media_type, display_order)
                    VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder})
                    """,
                    (product_id, image_url, media_type, idx)
                )
    
    conn.commit()
    conn.close()
    return True


def delete_manual_product(product_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    
    # Delete images first (cascade should handle this, but being explicit)
    cursor.execute(f"DELETE FROM product_images WHERE product_id = {placeholder}", (product_id,))
    cursor.execute(f"DELETE FROM manual_products WHERE id = {placeholder}", (product_id,))
    conn.commit()
    affected = cursor.rowcount
    conn.close()
    return affected > 0


def fetch_customer_by_email(email):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(f"SELECT * FROM customers WHERE email = {placeholder}", (email,))
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def fetch_customer_by_id(customer_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(f"SELECT * FROM customers WHERE id = {placeholder}", (customer_id,))
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def create_customer(payload):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_postgres = _is_postgres_backend()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    values = (
        payload["email"],
        payload["password_hash"],
        payload.get("first_name"),
        payload.get("last_name"),
        payload.get("phone"),
        now,
        now,
    )
    if is_postgres:
        cursor.execute(
            f"""
            INSERT INTO customers (
                email, password_hash, first_name, last_name, phone,
                created_at, updated_at
            ) VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder},
                      {placeholder}, {placeholder})
            RETURNING id
            """,
            values,
        )
        customer_id = cursor.fetchone()["id"]
    else:
        cursor.execute(
            f"""
            INSERT INTO customers (
                email, password_hash, first_name, last_name, phone,
                created_at, updated_at
            ) VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder},
                      {placeholder}, {placeholder})
            """,
            values,
        )
        customer_id = cursor.lastrowid
    conn.commit()
    conn.close()
    return customer_id


def update_customer_last_login(customer_id):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"""
        UPDATE customers
        SET last_login_at = {placeholder}, updated_at = {placeholder}
        WHERE id = {placeholder}
        """,
        (now, now, customer_id),
    )
    conn.commit()
    conn.close()


def update_customer_profile_self(customer_id, payload):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    cursor.execute(
        f"""
        UPDATE customers
        SET first_name = {placeholder},
            last_name = {placeholder},
            phone = {placeholder},
            updated_at = {placeholder}
        WHERE id = {placeholder}
        """,
        (
            payload.get("first_name"),
            payload.get("last_name"),
            payload.get("phone"),
            now,
            customer_id,
        ),
    )

    if cursor.rowcount == 0:
        conn.rollback()
        conn.close()
        return None

    cursor.execute(
        f"SELECT * FROM customers WHERE id = {placeholder}",
        (customer_id,),
    )
    updated = cursor.fetchone()
    conn.commit()
    conn.close()
    return dict(updated) if updated else None


def update_customer_password(customer_id, password_hash):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    cursor.execute(
        f"""
        UPDATE customers
        SET password_hash = {placeholder}, updated_at = {placeholder}
        WHERE id = {placeholder}
        """,
        (password_hash, now, customer_id),
    )
    conn.commit()
    affected = cursor.rowcount
    conn.close()
    return affected > 0


def count_recent_password_reset_requests(customer_id, request_ip, since_iso):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    cursor.execute(
        f"""
        SELECT COUNT(*) AS cnt
        FROM customer_password_resets
        WHERE customer_id = {placeholder}
          AND created_at >= {placeholder}
        """,
        (customer_id, since_iso),
    )
    customer_count = int((cursor.fetchone() or {}).get("cnt") or 0)

    ip_count = 0
    if request_ip:
        cursor.execute(
            f"""
            SELECT COUNT(*) AS cnt
            FROM customer_password_resets
            WHERE request_ip = {placeholder}
              AND created_at >= {placeholder}
            """,
            (request_ip, since_iso),
        )
        ip_count = int((cursor.fetchone() or {}).get("cnt") or 0)

    conn.close()
    return {
        "customer_count": customer_count,
        "ip_count": ip_count,
    }


def create_customer_password_reset(customer_id, token_hash, expires_at, request_ip=None, user_agent=None):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_postgres = _is_postgres_backend()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    values = (
        customer_id,
        token_hash,
        expires_at,
        request_ip,
        user_agent,
        now,
    )

    if is_postgres:
        cursor.execute(
            f"""
            INSERT INTO customer_password_resets (
                customer_id, token_hash, expires_at, request_ip, user_agent, created_at
            ) VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder})
            RETURNING id
            """,
            values,
        )
        reset_id = cursor.fetchone()["id"]
    else:
        cursor.execute(
            f"""
            INSERT INTO customer_password_resets (
                customer_id, token_hash, expires_at, request_ip, user_agent, created_at
            ) VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder})
            """,
            values,
        )
        reset_id = cursor.lastrowid

    conn.commit()
    conn.close()
    return reset_id


def consume_customer_password_reset(token_hash, now_iso):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    cursor.execute(
        f"""
        SELECT id, customer_id
        FROM customer_password_resets
        WHERE token_hash = {placeholder}
          AND used_at IS NULL
          AND expires_at > {placeholder}
        ORDER BY created_at DESC
        LIMIT 1
        """,
        (token_hash, now_iso),
    )
    row = cursor.fetchone()
    if not row:
        conn.close()
        return None

    cursor.execute(
        f"""
        UPDATE customer_password_resets
        SET used_at = {placeholder}
        WHERE id = {placeholder} AND used_at IS NULL
        """,
        (now_iso, row["id"]),
    )

    if cursor.rowcount == 0:
        conn.rollback()
        conn.close()
        return None

    conn.commit()
    conn.close()
    return row["customer_id"]


def revoke_customer_password_resets(customer_id):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"""
        UPDATE customer_password_resets
        SET used_at = {placeholder}
        WHERE customer_id = {placeholder}
          AND used_at IS NULL
        """,
        (now, customer_id),
    )
    conn.commit()
    conn.close()


def update_customer_admin(customer_id, payload):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    updates = []
    values = []

    for field in ("email", "first_name", "last_name", "phone", "admin_notes"):
        if field in payload:
            updates.append(f"{field} = {placeholder}")
            values.append(payload.get(field))

    updates.append(f"updated_at = {placeholder}")
    values.append(now)
    values.append(customer_id)

    cursor.execute(
        f"""
        UPDATE customers
        SET {', '.join(updates)}
        WHERE id = {placeholder}
        """,
        tuple(values),
    )

    if cursor.rowcount == 0:
        conn.rollback()
        conn.close()
        return None

    cursor.execute(
        f"SELECT * FROM customers WHERE id = {placeholder}",
        (customer_id,),
    )
    updated = cursor.fetchone()
    conn.commit()
    conn.close()
    return dict(updated) if updated else None


def delete_customer_admin(customer_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    cursor.execute(
        f"DELETE FROM customers WHERE id = {placeholder}",
        (customer_id,),
    )
    deleted = cursor.rowcount > 0
    conn.commit()
    conn.close()
    return deleted


def list_customer_addresses(customer_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"SELECT * FROM customer_addresses WHERE customer_id = {placeholder} ORDER BY is_default DESC, created_at DESC",
        (customer_id,),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def create_customer_address(customer_id, payload):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_postgres = _is_postgres_backend()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    values = (
        customer_id,
        payload.get("label"),
        payload.get("line1"),
        payload.get("line2"),
        payload.get("city"),
        payload.get("state"),
        payload.get("postal_code"),
        payload.get("country"),
        1 if payload.get("is_default") else 0,
        now,
        now,
    )
    if is_postgres:
        cursor.execute(
            f"""
            INSERT INTO customer_addresses (
                customer_id, label, line1, line2, city, state, postal_code, country,
                is_default, created_at, updated_at
            ) VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder},
                      {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder})
            RETURNING id
            """,
            values,
        )
        address_id = cursor.fetchone()["id"]
    else:
        cursor.execute(
            f"""
            INSERT INTO customer_addresses (
                customer_id, label, line1, line2, city, state, postal_code, country,
                is_default, created_at, updated_at
            ) VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder},
                      {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder})
            """,
            values,
        )
        address_id = cursor.lastrowid
    conn.commit()
    conn.close()
    return address_id


def upsert_customer_primary_address(customer_id, payload):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    cursor.execute(
        f"SELECT id FROM customer_addresses WHERE customer_id = {placeholder} ORDER BY is_default DESC, created_at ASC LIMIT 1",
        (customer_id,),
    )
    existing = cursor.fetchone()

    values = (
        payload.get("label") or "Primary",
        payload.get("line1"),
        payload.get("line2"),
        payload.get("city"),
        payload.get("state"),
        payload.get("postal_code"),
        payload.get("country"),
        now,
    )

    if existing:
        cursor.execute(
            f"""
            UPDATE customer_addresses
            SET label = {placeholder},
                line1 = {placeholder},
                line2 = {placeholder},
                city = {placeholder},
                state = {placeholder},
                postal_code = {placeholder},
                country = {placeholder},
                is_default = 1,
                updated_at = {placeholder}
            WHERE id = {placeholder}
            """,
            values + (existing["id"],),
        )
    else:
        cursor.execute(
            f"""
            INSERT INTO customer_addresses (
                customer_id, label, line1, line2, city, state, postal_code, country,
                is_default, created_at, updated_at
            ) VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder},
                      {placeholder}, {placeholder}, 1, {placeholder}, {placeholder})
            """,
            (
                customer_id,
                payload.get("label") or "Primary",
                payload.get("line1"),
                payload.get("line2"),
                payload.get("city"),
                payload.get("state"),
                payload.get("postal_code"),
                payload.get("country"),
                now,
                now,
            ),
        )

    conn.commit()
    conn.close()


def list_customer_favorites(customer_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"SELECT * FROM customer_favorites WHERE customer_id = {placeholder} ORDER BY created_at DESC",
        (customer_id,),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def add_customer_favorite(customer_id, product_type, product_id):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    try:
        cursor.execute(
            f"""
            INSERT INTO customer_favorites (customer_id, product_type, product_id, created_at)
            VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder})
            """,
            (customer_id, product_type, product_id, now),
        )
    except Exception:
        pass
    conn.commit()
    conn.close()


def remove_customer_favorite(customer_id, favorite_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"DELETE FROM customer_favorites WHERE id = {placeholder} AND customer_id = {placeholder}",
        (favorite_id, customer_id),
    )
    conn.commit()
    conn.close()


def list_customer_cart_items(customer_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"SELECT * FROM customer_cart_items WHERE customer_id = {placeholder} ORDER BY updated_at DESC",
        (customer_id,),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def upsert_customer_cart_item(customer_id, product_type, product_id, quantity):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    cursor.execute(
        f"""
        SELECT id, quantity FROM customer_cart_items
        WHERE customer_id = {placeholder} AND product_type = {placeholder} AND product_id = {placeholder}
        """,
        (customer_id, product_type, product_id),
    )
    row = cursor.fetchone()
    if row:
        cursor.execute(
            f"""
            UPDATE customer_cart_items
            SET quantity = {placeholder}, updated_at = {placeholder}
            WHERE id = {placeholder}
            """,
            (1, now, row["id"]),
        )
    else:
        cursor.execute(
            f"""
            INSERT INTO customer_cart_items (customer_id, product_type, product_id, quantity, created_at, updated_at)
            VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder})
            """,
            (customer_id, product_type, product_id, 1, now, now),
        )
    conn.commit()
    conn.close()


def update_customer_cart_item_quantity(customer_id, item_id, quantity):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    safe_quantity = 1 if int(quantity or 1) >= 1 else 1
    cursor.execute(
        f"""
        UPDATE customer_cart_items
        SET quantity = {placeholder}, updated_at = {placeholder}
        WHERE id = {placeholder} AND customer_id = {placeholder}
        """,
        (safe_quantity, now, item_id, customer_id),
    )
    conn.commit()
    conn.close()


def remove_customer_cart_item(customer_id, item_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"DELETE FROM customer_cart_items WHERE id = {placeholder} AND customer_id = {placeholder}",
        (item_id, customer_id),
    )
    conn.commit()
    conn.close()


def list_customer_orders(customer_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"SELECT * FROM customer_orders WHERE customer_id = {placeholder} ORDER BY created_at DESC",
        (customer_id,),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def create_customer_order_with_items(customer_id, order_payload, order_items):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    is_postgres = _is_postgres_backend()
    placeholder = "%s" if is_mysql else "?"
    now = datetime.utcnow().isoformat()

    insert_values = (
        customer_id,
        order_payload.get("order_number"),
        order_payload.get("status", "pending"),
        order_payload.get("subtotal_amount"),
        order_payload.get("shipping_amount"),
        order_payload.get("tax_amount"),
        order_payload.get("total_amount"),
        order_payload.get("currency", "USD"),
        order_payload.get("payment_status", "pending"),
        order_payload.get("payment_provider"),
        order_payload.get("payment_reference"),
        order_payload.get("customer_name"),
        order_payload.get("customer_email"),
        order_payload.get("shipping_address"),
        order_payload.get("billing_address"),
        order_payload.get("notes"),
        0,
        None,
        now,
        now,
    )

    if is_postgres:
        cursor.execute(
            f"""
            INSERT INTO customer_orders (
                customer_id, order_number, status,
                subtotal_amount, shipping_amount, tax_amount, total_amount, currency,
                payment_status, payment_provider, payment_reference,
                customer_name, customer_email,
                shipping_address, billing_address, notes,
                admin_seen, admin_seen_at,
                created_at, updated_at
            ) VALUES (
                {placeholder}, {placeholder}, {placeholder},
                {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder},
                {placeholder}, {placeholder}, {placeholder},
                {placeholder}, {placeholder},
                {placeholder}, {placeholder}, {placeholder},
                {placeholder}, {placeholder},
                {placeholder}, {placeholder}
            )
            RETURNING id
            """,
            insert_values,
        )
        order_id = cursor.fetchone()["id"]
    else:
        cursor.execute(
            f"""
            INSERT INTO customer_orders (
                customer_id, order_number, status,
                subtotal_amount, shipping_amount, tax_amount, total_amount, currency,
                payment_status, payment_provider, payment_reference,
                customer_name, customer_email,
                shipping_address, billing_address, notes,
                admin_seen, admin_seen_at,
                created_at, updated_at
            ) VALUES (
                {placeholder}, {placeholder}, {placeholder},
                {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder},
                {placeholder}, {placeholder}, {placeholder},
                {placeholder}, {placeholder},
                {placeholder}, {placeholder}, {placeholder},
                {placeholder}, {placeholder},
                {placeholder}, {placeholder}
            )
            """,
            insert_values,
        )
        order_id = cursor.lastrowid

    for item in order_items:
        cursor.execute(
            f"""
            INSERT INTO customer_order_items (order_id, product_type, product_id, title, price, quantity, image_url)
            VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder})
            """,
            (
                order_id,
                item.get("product_type"),
                str(item.get("product_id")),
                item.get("title"),
                item.get("price"),
                int(item.get("quantity", 1)),
                item.get("image_url"),
            ),
        )

    cursor.execute(
        f"""
        INSERT INTO customer_order_events (order_id, event_type, event_detail, payload, created_at)
        VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder})
        """,
        (
            order_id,
            "order.placed",
            f"Order placed with payment_status={order_payload.get('payment_status', 'pending')}",
            None,
            now,
        ),
    )

    cursor.execute(
        f"DELETE FROM customer_cart_items WHERE customer_id = {placeholder}",
        (customer_id,),
    )

    conn.commit()
    conn.close()
    return order_id


def list_admin_recent_orders(limit=20, unseen_only=False):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    limit_value = max(1, min(int(limit or 20), 100))

    where_clause = "WHERE o.admin_seen = 0" if unseen_only else ""
    cursor.execute(
        f"""
        SELECT
            o.*, c.first_name, c.last_name,
            c.email AS account_email,
            COUNT(oi.id) AS item_count
        FROM customer_orders o
        LEFT JOIN customers c ON c.id = o.customer_id
        LEFT JOIN customer_order_items oi ON oi.order_id = o.id
        {where_clause}
        GROUP BY o.id, c.first_name, c.last_name, c.email
        ORDER BY o.created_at DESC
        LIMIT {placeholder}
        """,
        (limit_value,),
    )
    rows = cursor.fetchall()
    conn.close()
    orders = [dict(row) for row in rows]
    events_by_order_id = list_customer_order_events_for_orders([entry.get("id") for entry in orders], limit_per_order=8)
    for entry in orders:
        entry["events"] = events_by_order_id.get(entry.get("id"), [])
    return orders


def mark_customer_order_admin_seen(order_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    now = datetime.utcnow().isoformat()

    cursor.execute(
        f"""
        UPDATE customer_orders
        SET admin_seen = 1, admin_seen_at = {placeholder}, updated_at = {placeholder}
        WHERE id = {placeholder}
        """,
        (now, now, order_id),
    )
    updated = cursor.rowcount > 0
    conn.commit()
    conn.close()
    return updated


def get_customer_order_id_by_payment_reference(payment_reference):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    cursor.execute(
        f"SELECT id FROM customer_orders WHERE payment_reference = {placeholder} LIMIT 1",
        (payment_reference,),
    )
    row = cursor.fetchone()
    conn.close()
    if not row:
        return None
    return row.get("id") if isinstance(row, dict) else row["id"]


def append_customer_order_event(order_id, event_type, event_detail=None, payload=None):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    now = datetime.utcnow().isoformat()

    cursor.execute(
        f"""
        INSERT INTO customer_order_events (order_id, event_type, event_detail, payload, created_at)
        VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder})
        """,
        (order_id, event_type, event_detail, payload, now),
    )
    conn.commit()
    conn.close()


def list_customer_order_events(order_id, limit=20):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    limit_value = max(1, min(int(limit or 20), 100))

    cursor.execute(
        f"""
        SELECT id, order_id, event_type, event_detail, payload, created_at
        FROM customer_order_events
        WHERE order_id = {placeholder}
        ORDER BY created_at DESC
        LIMIT {placeholder}
        """,
        (order_id, limit_value),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def list_customer_order_events_for_orders(order_ids, limit_per_order=5):
    normalized_ids = [int(oid) for oid in order_ids if oid is not None]
    if not normalized_ids:
        return {}

    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    is_postgres = _is_postgres_backend()
    placeholder = "%s" if is_mysql else "?"
    per_order_cap = max(1, min(int(limit_per_order or 5), 25))

    if is_postgres:
        cursor.execute(
            f"""
            SELECT id, order_id, event_type, event_detail, payload, created_at
            FROM (
                SELECT
                    id,
                    order_id,
                    event_type,
                    event_detail,
                    payload,
                    created_at,
                    ROW_NUMBER() OVER (PARTITION BY order_id ORDER BY created_at DESC) AS rn
                FROM customer_order_events
                WHERE order_id = ANY({placeholder})
            ) ranked
            WHERE rn <= {placeholder}
            ORDER BY order_id, created_at DESC
            """,
            (normalized_ids, per_order_cap),
        )
    else:
        placeholders = ", ".join([placeholder] * len(normalized_ids))
        cursor.execute(
            f"""
            SELECT id, order_id, event_type, event_detail, payload, created_at
            FROM customer_order_events
            WHERE order_id IN ({placeholders})
            ORDER BY created_at DESC
            """,
            tuple(normalized_ids),
        )

    rows = cursor.fetchall()
    conn.close()

    grouped = {order_id: [] for order_id in normalized_ids}
    for row in rows:
        payload = dict(row)
        order_id = payload.get("order_id")
        if order_id not in grouped:
            grouped[order_id] = []
        if len(grouped[order_id]) >= per_order_cap:
            continue
        grouped[order_id].append(payload)
    return grouped


def update_customer_order_payment_by_reference(payment_reference, payment_status, order_status=None):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    now = datetime.utcnow().isoformat()

    if order_status is None:
        cursor.execute(
            f"""
            UPDATE customer_orders
            SET payment_status = {placeholder}, updated_at = {placeholder}
            WHERE payment_reference = {placeholder}
            """,
            (payment_status, now, payment_reference),
        )
    else:
        cursor.execute(
            f"""
            UPDATE customer_orders
            SET payment_status = {placeholder}, status = {placeholder}, updated_at = {placeholder}
            WHERE payment_reference = {placeholder}
            """,
            (payment_status, order_status, now, payment_reference),
        )

    updated = cursor.rowcount > 0
    conn.commit()
    conn.close()
    return updated


def list_customer_order_items(customer_id, order_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"""
        SELECT oi.*
        FROM customer_order_items oi
        JOIN customer_orders o ON o.id = oi.order_id
        WHERE oi.order_id = {placeholder} AND o.customer_id = {placeholder}
        """,
        (order_id, customer_id),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def has_verified_purchase(customer_id, product_type, product_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"""
        SELECT oi.id
        FROM customer_order_items oi
        JOIN customer_orders o ON o.id = oi.order_id
        WHERE o.customer_id = {placeholder}
          AND oi.product_type = {placeholder}
          AND oi.product_id = {placeholder}
        LIMIT 1
        """,
        (customer_id, product_type, product_id),
    )
    row = cursor.fetchone()
    conn.close()
    return bool(row)


def list_customer_review_options(customer_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"""
        SELECT
            oi.product_type,
            oi.product_id,
            MAX(o.created_at) AS last_purchased_at,
            MAX(COALESCE(oi.title, '')) AS title,
            MAX(COALESCE(oi.image_url, '')) AS image_url
        FROM customer_order_items oi
        JOIN customer_orders o ON o.id = oi.order_id
        WHERE o.customer_id = {placeholder}
        GROUP BY oi.product_type, oi.product_id
        ORDER BY last_purchased_at DESC
        """,
        (customer_id,),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def list_reviews_for_product(product_type, product_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"""
                SELECT
                        r.*, c.first_name, c.last_name,
                        (
                                SELECT COALESCE(oi.image_url, '')
                                FROM customer_order_items oi
                                WHERE oi.product_type = r.product_type
                                    AND oi.product_id = r.product_id
                                    AND COALESCE(oi.image_url, '') <> ''
                                ORDER BY oi.id DESC
                                LIMIT 1
                        ) AS product_image_url,
                        (
                                SELECT COALESCE(oi.title, '')
                                FROM customer_order_items oi
                                WHERE oi.product_type = r.product_type
                                    AND oi.product_id = r.product_id
                                    AND COALESCE(oi.title, '') <> ''
                                ORDER BY oi.id DESC
                                LIMIT 1
                        ) AS product_title
        FROM customer_reviews r
        JOIN customers c ON c.id = r.customer_id
        WHERE r.product_type = {placeholder}
          AND r.product_id = {placeholder}
          AND r.status = 'approved'
        ORDER BY r.created_at DESC
        """,
        (product_type, product_id),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def list_recent_reviews(limit=10):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    safe_limit = max(1, min(int(limit or 10), 50))
    cursor.execute(
        f"""
                SELECT
                        r.*, c.first_name, c.last_name,
                        (
                                SELECT COALESCE(oi.image_url, '')
                                FROM customer_order_items oi
                                WHERE oi.product_type = r.product_type
                                    AND oi.product_id = r.product_id
                                    AND COALESCE(oi.image_url, '') <> ''
                                ORDER BY oi.id DESC
                                LIMIT 1
                        ) AS product_image_url,
                        (
                                SELECT COALESCE(oi.title, '')
                                FROM customer_order_items oi
                                WHERE oi.product_type = r.product_type
                                    AND oi.product_id = r.product_id
                                    AND COALESCE(oi.title, '') <> ''
                                ORDER BY oi.id DESC
                                LIMIT 1
                        ) AS product_title
        FROM customer_reviews r
        JOIN customers c ON c.id = r.customer_id
        WHERE r.status = 'approved'
        ORDER BY r.created_at DESC
        LIMIT {placeholder}
        """,
        (safe_limit,),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def list_customer_reviews(customer_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"SELECT * FROM customer_reviews WHERE customer_id = {placeholder} ORDER BY created_at DESC",
        (customer_id,),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def list_admin_reviews(limit=200, status=None):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    safe_limit = max(1, min(int(limit or 200), 500))
    status_filter = str(status or "").strip().lower()

    if status_filter:
        cursor.execute(
            f"""
            SELECT r.*, c.first_name, c.last_name
            FROM customer_reviews r
            JOIN customers c ON c.id = r.customer_id
            WHERE r.status = {placeholder}
            ORDER BY r.created_at DESC
            LIMIT {placeholder}
            """,
            (status_filter, safe_limit),
        )
    else:
        cursor.execute(
            f"""
            SELECT r.*, c.first_name, c.last_name
            FROM customer_reviews r
            JOIN customers c ON c.id = r.customer_id
            ORDER BY r.created_at DESC
            LIMIT {placeholder}
            """,
            (safe_limit,),
        )

    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]


def update_admin_review(review_id, payload):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    updates = []
    values = []

    if "rating" in payload:
        updates.append(f"rating = {placeholder}")
        values.append(int(payload.get("rating") or 0))
    if "title" in payload:
        updates.append(f"title = {placeholder}")
        values.append(payload.get("title"))
    if "body" in payload:
        updates.append(f"body = {placeholder}")
        values.append(payload.get("body"))
    if "status" in payload:
        updates.append(f"status = {placeholder}")
        values.append(str(payload.get("status") or "").strip().lower())

    if not updates:
        conn.close()
        return False

    updates.append(f"updated_at = {placeholder}")
    values.append(now)
    values.append(review_id)

    cursor.execute(
        f"""
        UPDATE customer_reviews
        SET {", ".join(updates)}
        WHERE id = {placeholder}
        """,
        tuple(values),
    )
    updated = cursor.rowcount > 0
    conn.commit()
    conn.close()
    return updated


def delete_admin_review(review_id):
    conn = get_db()
    cursor = conn.cursor()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    cursor.execute(
        f"DELETE FROM customer_reviews WHERE id = {placeholder}",
        (review_id,),
    )
    deleted = cursor.rowcount > 0
    conn.commit()
    conn.close()
    return deleted


def create_customer_review(customer_id, payload, verified_purchase):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_postgres = _is_postgres_backend()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"
    values = (
        customer_id,
        payload["product_type"],
        payload["product_id"],
        payload["rating"],
        payload.get("title"),
        payload.get("body"),
        1 if verified_purchase else 0,
        "approved" if verified_purchase else "pending",
        now,
        now,
    )
    if is_postgres:
        cursor.execute(
            f"""
            INSERT INTO customer_reviews (
                customer_id, product_type, product_id, rating, title, body,
                verified_purchase, status, created_at, updated_at
            ) VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder},
                      {placeholder}, {placeholder}, {placeholder}, {placeholder})
            RETURNING id
            """,
            values,
        )
        review_id = cursor.fetchone()["id"]
    else:
        cursor.execute(
            f"""
            INSERT INTO customer_reviews (
                customer_id, product_type, product_id, rating, title, body,
                verified_purchase, status, created_at, updated_at
            ) VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder},
                      {placeholder}, {placeholder}, {placeholder}, {placeholder})
            """,
            values,
        )
        review_id = cursor.lastrowid
    conn.commit()
    conn.close()
    return review_id


def update_customer_review(customer_id, review_id, payload):
    conn = get_db()
    cursor = conn.cursor()
    now = datetime.utcnow().isoformat()
    is_mysql = _use_mysql()
    placeholder = "%s" if is_mysql else "?"

    updates = []
    values = []

    if "rating" in payload:
        updates.append(f"rating = {placeholder}")
        values.append(int(payload.get("rating") or 0))
    if "title" in payload:
        updates.append(f"title = {placeholder}")
        values.append(payload.get("title"))
    if "body" in payload:
        updates.append(f"body = {placeholder}")
        values.append(payload.get("body"))

    if not updates:
        conn.close()
        return False

    updates.append(f"status = {placeholder}")
    values.append("pending")
    updates.append(f"updated_at = {placeholder}")
    values.append(now)
    values.extend([review_id, customer_id])

    cursor.execute(
        f"""
        UPDATE customer_reviews
        SET {", ".join(updates)}
        WHERE id = {placeholder} AND customer_id = {placeholder}
        """,
        tuple(values),
    )
    updated = cursor.rowcount > 0
    conn.commit()
    conn.close()
    return updated
